import type { CertificateItem } from "@/types";

/**
 * Every field here was read off the certificate itself, not inferred from a
 * filename. The PDFs were rendered and read; the HackerRank one arrived as an
 * image already. Where a document carries no single issue date (the DevTown
 * set prints a programme duration in the date slot), `issued` is left unset
 * rather than guessed at, and the duration goes in `detail`.
 *
 * Previews are generated by `scripts/render-certificate-previews.mjs`. The
 * original PDFs ship alongside them and stay reachable from the viewer.
 */
export const certificates: CertificateItem[] = [
  {
    id: "devtown-internship",
    title: "Certificate of Internship Completion",
    issuer: "DevTown",
    detail: "Full Stack Web Developer · May 2024 to Sep 2024",
    verifyUrl: "https://cert.devtown.in/verify/WYWqN",
    kind: "certificate",
    image: "/certificates/devtown-internship.jpg",
    documentUrl: "/certificates/devtown-internship.pdf",
    width: 1126,
    height: 1600,
  },
  {
    id: "devtown-course",
    title: "Certificate of Course Completion",
    issuer: "DevTown",
    detail: "Full Stack Web Development · May 2024 to Sep 2024",
    verifyUrl: "https://cert.devtown.in/verify/Z1x10L4",
    kind: "certificate",
    image: "/certificates/devtown-course.jpg",
    documentUrl: "/certificates/devtown-course.pdf",
    width: 1600,
    height: 1136,
  },
  {
    id: "hackerrank-python",
    title: "Python (Basic)",
    issuer: "HackerRank",
    issued: "4 Sep 2023",
    credentialId: "1C52FF7B0BFF",
    detail: "Skill certification test",
    kind: "certificate",
    image: "/certificates/hackerrank-python-basic.png",
    width: 1600,
    height: 1200,
  },
  {
    id: "internselite-internship",
    title: "Certificate of Internship",
    issuer: "InternsElite",
    issued: "25 Aug 2023",
    credentialId: "IT/2023/WD/1375",
    detail: "Web Development · 1 Jun 2023 to 31 Jul 2023",
    kind: "certificate",
    image: "/certificates/internselite-internship.jpg",
    documentUrl: "/certificates/internselite-internship.pdf",
    width: 1600,
    height: 1147,
  },
  {
    id: "internselite-training",
    title: "Certificate of Training",
    issuer: "InternsElite",
    issued: "25 Aug 2023",
    detail: "Industrial training in Web Development · 1 Jun 2023 to 31 Jul 2023",
    kind: "certificate",
    image: "/certificates/internselite-training.jpg",
    documentUrl: "/certificates/internselite-training.pdf",
    width: 1600,
    height: 1067,
  },
  {
    id: "cisco-cyberops",
    title: "CyberOps Associate",
    issuer: "Cisco Networking Academy",
    issued: "9 Jan 2023",
    detail: "Course completion · NIIT Foundation, India",
    kind: "certificate",
    image: "/certificates/cisco-cyberops-certificate.jpg",
    documentUrl: "/certificates/cisco-cyberops-certificate.pdf",
    width: 1600,
    height: 1131,
  },
  {
    id: "devtown-lor",
    title: "Letter of Recommendation",
    issuer: "DevTown",
    detail: "Full Stack Web Development · May 2024 to Sep 2024",
    verifyUrl: "https://cert.devtown.in/verify/Z27QiMb",
    kind: "letter",
    image: "/certificates/devtown-lor.jpg",
    documentUrl: "/certificates/devtown-lor.pdf",
    width: 1126,
    height: 1600,
  },
  {
    id: "cisco-cyberops-letter",
    title: "CyberOps Associate Letter",
    issuer: "Cisco Networking Academy",
    issued: "9 Jan 2023",
    detail: "Accompanies the course completion certificate",
    kind: "letter",
    image: "/certificates/cisco-cyberops-letter.jpg",
    documentUrl: "/certificates/cisco-cyberops-letter.pdf",
    width: 1131,
    height: 1600,
  },
];
